name: New Project
description: Create a new project from this template.
title: "Initialize new project"
body:
  - type: input
    id: project_name
    attributes:
      label: Project Name
      description: The name for your new project.
    validations:
      required: true
  - type: input
    id: author_name
    attributes:
      label: Author Name
      description: Your name or organization name.
    validations:
      required: true
