name: Initialize Project
on:
  issues:
    types: [opened]
jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create project from template
        if: github.event.issue.title == 'Initialize new project'
        run: |
          # Use a templating tool like `j2cli` or a custom script
          # to replace the placeholders.
          # Here we use a simple sed command as an example.
          PROJECT_NAME=$(echo '${{ github.event.issue.body }}' | grep 'Project Name:' | sed 's/.*: //')
          AUTHOR_NAME=$(echo '${{ github.event.issue.body }}' | grep 'Author Name:' | sed 's/.*: //')
          
          sed -i "s/{{project_name}}/$PROJECT_NAME/g" config.json.template
          sed -i "s/{{author_name}}/$AUTHOR_NAME/g" config.json.template
          mv config.json.template config.json
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add config.json
          git commit -m "feat: Initialize project with user details"
          git push
